# Generated by Django 4.0.4 on 2022-06-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category name ', max_length=180, verbose_name='name')),
                ('des', models.TextField(blank=True, max_length=340, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/frontbage/category', verbose_name='image')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='You should write some words indicating the content of the article in English', max_length=200, verbose_name=' url')),
            ],
        ),
    ]
