# Generated by Django 4.0.4 on 2022-06-01 02:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/blog/frontbage/about', verbose_name='image')),
                ('name', models.CharField(default='user', max_length=70, verbose_name='name')),
                ('short_des', models.CharField(default='Senior blog writer', max_length=70, verbose_name='short description')),
                ('des', models.TextField(max_length=300, verbose_name='description')),
                ('fb_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook link')),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Twitter link')),
                ('github_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Github link')),
            ],
            options={
                'verbose_name_plural': 'AboutAuthor',
            },
        ),
        migrations.CreateModel(
            name='AdsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_code_1', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (1) ')),
                ('ad_code_2', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (2) ')),
                ('ad_code_3', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (3) ')),
                ('ad_code_4', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (4) ')),
                ('ad_code_5', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (5) ')),
                ('ad_code_6', models.TextField(blank=True, default='Enter ads code', null=True, verbose_name=' ad code (6) ')),
            ],
            options={
                'verbose_name_plural': 'AdsWidget',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(blank=True, max_length=4000, verbose_name='content')),
                ('image', models.ImageField(upload_to='media/blog/frontbage', verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('views', models.IntegerField(default=0, verbose_name=' views')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='You should write some words indicating the content of the article in English', max_length=200, verbose_name=' url')),
                ('author_en', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='author_en', to=settings.AUTH_USER_MODEL, verbose_name=' author')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NameWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_post', models.CharField(default='Popular Posts', max_length=90, verbose_name='popular post')),
                ('post_catgories', models.CharField(default='Post Catgories', max_length=90, verbose_name='post catgories')),
                ('newsletter', models.CharField(default='Newsletter', max_length=90, verbose_name='newsletter')),
                ('tag_clouds', models.CharField(default='Tag Clouds', max_length=90, verbose_name=' tag clouds')),
            ],
            options={
                'verbose_name_plural': 'NameWidget',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('body', models.TextField(max_length=500, verbose_name='comment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('post', models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog_eng.blog', verbose_name='post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
