# Generated by Django 4.0.4 on 2022-06-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_eng', '0001_initial'),
        ('tag_eng', '0001_initial'),
        ('blog_eng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category_eng',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_category_en', to='category_eng.category', verbose_name=' category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_eng',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_tag_en', to='tag_eng.tag', verbose_name='tag'),
            preserve_default=False,
        ),
    ]
