# Generated by Django 4.0.4 on 2022-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBarEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, default='/', help_text='eg: /page', max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'MenuBarEn',
            },
        ),
        migrations.RenameModel(
            old_name='MenuBar',
            new_name='MenuBarAr',
        ),
        migrations.AlterModelOptions(
            name='menubarar',
            options={'verbose_name_plural': 'MenuBarAr'},
        ),
    ]
