# Generated by Django 4.0.4 on 2022-05-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEn', '0002_menubaren_rename_menubar_menubarar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuBarAr',
        ),
        migrations.DeleteModel(
            name='MenuBarEn',
        ),
    ]
