# Generated by Django 4.0.4 on 2022-05-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='title_ar',
        ),
    ]
