# Generated by Django 4.0.4 on 2022-05-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAr', '0002_remove_blogs_content_ar_remove_blogs_title_ar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='slug',
            new_name='arabic_slugify',
        ),
    ]
