# Generated by Django 4.0.4 on 2022-05-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAr', '0003_rename_slug_blogs_arabic_slugify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='arabic_slugify',
            new_name='slug',
        ),
    ]
