# Generated by Django 4.0.4 on 2022-05-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAr', '0004_rename_arabic_slugify_blogs_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuBar',
        ),
    ]
