# Generated by Django 4.0.1 on 2022-01-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_description_profile_email_profile_fb_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='User.email', max_length=300, null=True),
        ),
    ]
