# Generated by Django 4.0.1 on 2022-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media\\profile\\p1.jpg', null=True, upload_to='profile/'),
        ),
    ]
