# Generated by Django 4.0.1 on 2022-01-25 19:30

import blog.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/blog/frontbage/about')),
                ('name', models.CharField(default='user', max_length=70)),
                ('short_des', models.CharField(default='Senior blog writer', max_length=70)),
                ('des', models.TextField(max_length=300)),
                ('fb_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('github_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_code_1', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_2', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_3', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_4', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_5', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_6', models.TextField(blank=True, default='Enter ads code', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=4000)),
                ('image', models.ImageField(upload_to='media/blog/frontbage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter category name ', max_length=80)),
                ('des', models.TextField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/frontbage/category')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_post', models.CharField(default='Popular Posts', max_length=90)),
                ('post_catgories', models.CharField(default='Post Catgories', max_length=90)),
                ('newsletter', models.CharField(default='Newsletter', max_length=90)),
                ('tag_clouds', models.CharField(default='Tag Clouds', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter tag name ', max_length=80)),
                ('des', models.TextField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/frontbage/tag')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=blog.models.Category, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ForeignKey(default=blog.models.Tag, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='blog.tag'),
        ),
    ]
