# Generated by Django 4.0.1 on 2022-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_ar',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='content_ar'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title_ar'),
        ),
    ]
