# Generated by Django 4.0.1 on 2022-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutauthor',
            options={'verbose_name_plural': 'AboutAuthor'},
        ),
        migrations.AlterModelOptions(
            name='adswidget',
            options={'verbose_name_plural': 'AdsWidget'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at', 'title'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='menubar',
            options={'verbose_name_plural': 'MenuBar'},
        ),
        migrations.AlterModelOptions(
            name='namewidget',
            options={'verbose_name_plural': 'NameWidget'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ar',
            field=models.TextField(blank=True, default=models.TextField(blank=True, max_length=4000, verbose_name='content'), max_length=4000, verbose_name='content_ar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(default=models.CharField(max_length=50, verbose_name='title'), max_length=50, verbose_name='title_ar'),
        ),
    ]
