# Generated by Django 4.0.1 on 2022-01-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Author',
        ),
    ]
