# Generated by Django 4.0.1 on 2022-01-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_1', models.CharField(blank=True, max_length=100, null=True)),
                ('url_1', models.URLField(blank=True, null=True)),
                ('menu_2', models.CharField(blank=True, max_length=100, null=True)),
                ('url_2', models.URLField(blank=True, null=True)),
                ('menu_3', models.CharField(blank=True, max_length=100, null=True)),
                ('url_3', models.URLField(blank=True, null=True)),
                ('menu_4', models.CharField(blank=True, max_length=100, null=True)),
                ('url_4', models.URLField(blank=True, null=True)),
                ('menu_5', models.CharField(blank=True, max_length=100, null=True)),
                ('url_5', models.URLField(blank=True, null=True)),
                ('menu_6', models.CharField(blank=True, max_length=100, null=True)),
                ('url_6', models.URLField(blank=True, null=True)),
                ('menu_7', models.CharField(blank=True, max_length=100, null=True)),
                ('url_7', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
