# Generated by Django 4.0.1 on 2022-01-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menubar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menubar',
            old_name='menu_1',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menubar',
            old_name='url_1',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_2',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_3',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_4',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_5',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_6',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='menu_7',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_2',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_3',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_4',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_5',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_6',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='url_7',
        ),
    ]
