# Generated by Django 4.0.1 on 2022-04-27 01:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_aboutauthor_options_alter_adswidget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(max_length=50, verbose_name='title_ar'),
        ),
        migrations.CreateModel(
            name='BlogAr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar1', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='title_ar1', to='blog.blog', verbose_name=' title_ar')),
            ],
            options={
                'verbose_name_plural': 'BlogAr',
            },
        ),
    ]
