# Generated by Django 4.0.1 on 2022-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_about_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
