# Generated by Django 4.0.1 on 2022-04-27 01:02

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_title_ar_blogar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogar',
            name='title_ar1',
            field=models.ForeignKey(default=blog.models.Blog, on_delete=django.db.models.deletion.CASCADE, related_name='title_ar1', to='blog.blog', verbose_name=' title_ar'),
        ),
    ]
