# Generated by Django 4.0.1 on 2022-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/blog/about')),
                ('name', models.CharField(max_length=70)),
                ('short_des', models.CharField(default='Senior blog writer', max_length=70)),
                ('des', models.TextField(max_length=300)),
                ('fb_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('github_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
