# Generated by Django 4.0.1 on 2022-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogar_title_ar1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_ar',
            field=models.TextField(blank=True, max_length=4000, verbose_name='content_ar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='title_ar'),
        ),
        migrations.DeleteModel(
            name='BlogAr',
        ),
    ]
