# Generated by Django 4.0.1 on 2022-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sas',
            name='des',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sas',
            name='fb_link',
            field=models.URLField(blank=True, default='www', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sas',
            name='github_link',
            field=models.URLField(blank=True, default='www', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sas',
            name='image',
            field=models.ImageField(default='', upload_to='media/blog/about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sas',
            name='name',
            field=models.CharField(default='user', max_length=70),
        ),
        migrations.AddField(
            model_name='sas',
            name='short_des',
            field=models.CharField(default='Senior blog writer', max_length=70),
        ),
        migrations.AddField(
            model_name='sas',
            name='twitter_link',
            field=models.URLField(blank=True, default='www', max_length=300, null=True),
        ),
    ]
