# Generated by Django 4.0.1 on 2022-01-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sas_des_sas_fb_link_sas_github_link_sas_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAuthor',
        ),
    ]
