# Generated by Django 4.0.1 on 2022-01-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_aboutauthor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sas',
            new_name='AboutAuthor',
        ),
    ]
