# Generated by Django 4.0.1 on 2022-01-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_sas_aboutauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameWedgit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_post', models.CharField(default='Popular Posts', max_length=90)),
                ('post_catgories', models.CharField(default='Post Catgories', max_length=90)),
                ('newsletter', models.CharField(default='Newsletter', max_length=90)),
                ('tag_clouds', models.CharField(default='Tag Clouds', max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutauthor',
            name='fb_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutauthor',
            name='github_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutauthor',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
