# Generated by Django 4.0.1 on 2022-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_namewedgit_alter_aboutauthor_fb_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_code_1', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_2', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_3', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_4', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_5', models.TextField(blank=True, default='Enter ads code', null=True)),
                ('ad_code_6', models.TextField(blank=True, default='Enter ads code', null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NameWedgit',
            new_name='NameWidget',
        ),
    ]
