# Generated by Django 4.0.1 on 2022-01-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_slug_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='media/blog/frontbage/category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default=' ', upload_to='media/blog/frontbage/tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutauthor',
            name='image',
            field=models.ImageField(upload_to='media/blog/frontbage/about'),
        ),
    ]
