# Generated by Django 4.0.1 on 2022-01-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_image_tag_image_alter_aboutauthor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='des',
            field=models.TextField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='des',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
