# Generated by Django 4.0.1 on 2022-01-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_des_tag_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='des',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='des',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/frontbage/tag'),
        ),
    ]
