# Generated by Django 4.0.1 on 2022-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_ipmodel_remove_blog_post_views_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
