# Generated by Django 4.0.1 on 2022-01-09 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='call us now', max_length=50, null=True)),
                ('des', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/index/call/')),
                ('phone', models.CharField(max_length=50)),
                ('experience', models.CharField(blank=True, default=' Years Experience Working', max_length=60, null=True)),
                ('years', models.IntegerField(blank=True, default='3', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_name', models.CharField(blank=True, max_length=50, null=True)),
                ('big_dec', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=60)),
                ('des', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/index/clientsay/')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/following/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=220)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/index/FollowMe/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('fb_link', models.URLField(blank=True, max_length=400, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=400, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=400, null=True)),
                ('about', models.DateTimeField(default=django.utils.timezone.now)),
                ('about_txt', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_name', models.CharField(default='hello', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/index/hello/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/latest/')),
            ],
        ),
        migrations.CreateModel(
            name='MySelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/index/myself/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/popular/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_name', models.CharField(blank=True, max_length=50, null=True)),
                ('big_dec', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/index/service/')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/upcoming/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
