# Generated by Django 4.0.4 on 2022-06-01 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='call us now', max_length=50, verbose_name='title')),
                ('des', models.TextField(blank=True, max_length=400, null=True, verbose_name='des')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/call/', verbose_name='image')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('experience', models.CharField(blank=True, default=' Years Experience Working', max_length=60, null=True, verbose_name='experience')),
                ('years', models.IntegerField(blank=True, default='3', null=True, verbose_name='years')),
            ],
            options={
                'verbose_name_plural': 'Call',
            },
        ),
        migrations.CreateModel(
            name='ClientSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='big_name')),
                ('big_dec', models.TextField(blank=True, max_length=300, null=True, verbose_name='big_dec')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('des', models.TextField(max_length=400, verbose_name='des')),
                ('image', models.ImageField(upload_to='media/index/clientsay/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'ClientSay',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='address')),
                ('address_details', models.CharField(blank=True, max_length=90, null=True, verbose_name='address_details')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('work_time', models.CharField(blank=True, default='Mon to Fri 9am to 6 pm', max_length=70, verbose_name='work_time')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('Send_any_time', models.CharField(blank=True, default='Send us your query anytime!', max_length=70, verbose_name='Send_any_time')),
            ],
            options={
                'verbose_name_plural': 'ContactInfo',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='FooterHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=220, verbose_name='site_name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/index/FollowMe/', verbose_name='logo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('follow_me_text_name', models.CharField(blank=True, default='follow_me_text_name', max_length=220, null=True)),
                ('fb_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='fb_link')),
                ('twitter_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='twitter_link')),
                ('instagram_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='instagram_link')),
                ('Copyright', models.CharField(blank=True, default='Copyright', max_length=220, null=True, verbose_name='Copyright')),
                ('all_rights_reserved', models.CharField(blank=True, default=' All rights reserved', max_length=220, null=True, verbose_name='all_rights_reserved')),
                ('Copyright_txt_1', models.CharField(blank=True, default='This template is made with', max_length=220, null=True, verbose_name='Copyright_txt_1')),
                ('Copyright_txt_2', models.CharField(blank=True, default='by', max_length=220, null=True, verbose_name='Copyright_txt_2')),
                ('Copyright_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Copyright_link')),
                ('Copyright_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Copyright_date')),
            ],
            options={
                'verbose_name_plural': 'FooterHeader',
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_name', models.CharField(default='hello', max_length=50, verbose_name='hello_name')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('des', models.TextField(blank=True, max_length=400, verbose_name='des')),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to='media/index/hello/', verbose_name='image_banner')),
                ('cv', models.CharField(default='Get CV', max_length=50, verbose_name='cv')),
                ('cv_link', models.URLField(blank=True, max_length=2000, null=True, verbose_name='cv_link')),
                ('hire', models.CharField(default='Hire Me', max_length=50, verbose_name='hire')),
                ('hire_link', models.URLField(blank=True, max_length=2000, null=True, verbose_name='hire_link')),
                ('back_banner', models.ImageField(blank=True, null=True, upload_to='media/index/hello/', verbose_name='back_banner')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'Hello',
            },
        ),
        migrations.CreateModel(
            name='MenuBarAr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, default='/', help_text='eg: /page', max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'MenuBar Ar',
            },
        ),
        migrations.CreateModel(
            name='MenuBarEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, default='/', help_text='eg: /page', max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'MenuBar En',
            },
        ),
        migrations.CreateModel(
            name='MySelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('des', models.TextField(blank=True, max_length=400, verbose_name='des')),
                ('download_cv', models.CharField(default=' Download CV', max_length=50, verbose_name='download_cv')),
                ('download_link', models.URLField(blank=True, max_length=2000, null=True, verbose_name='download_link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/myself/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'MySelf',
            },
        ),
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('data_added', models.DateTimeField(auto_now_add=True, verbose_name='data_added')),
            ],
            options={
                'verbose_name_plural': 'NewsletterUser',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='big_name')),
                ('big_dec', models.TextField(blank=True, max_length=300, null=True, verbose_name='big_dec')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('des', models.TextField(max_length=400, verbose_name='des')),
                ('image', models.ImageField(upload_to='media/index/service/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=60, verbose_name='skill_title')),
                ('skill_percentage', models.IntegerField(verbose_name='skill_percentage')),
                ('image', models.ImageField(upload_to='media/index/Skill/', verbose_name='image')),
                ('color_bar', models.CharField(choices=[('#800000', 'Maroon'), ('#728FCE', 'LightPurple'), ('#800080', 'Purple'), ('#4863A0', 'Azure'), ('#566D7E', 'Marble'), ('#CD7F32', ' Bronze'), ('#FF8040', 'Orange'), ('#15317E ', 'Lapis'), ('#1E90FF', 'DeepSkyBlue'), ('#0041C2', '  Canary'), ('#7BCCB5', 'BlueGreen'), ('#6A5ACD', 'SlateBlue'), ('#8A2BE2 ', 'BlueViolet'), ('#57FEFF', 'Zircon')], max_length=60, verbose_name='color')),
            ],
            options={
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Latest', 'Latest'), ('Following', 'Following'), ('Upcoming', 'Upcoming')], max_length=50, null=True, verbose_name='status')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('des', models.TextField(blank=True, max_length=300, null=True, verbose_name='des')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/popular/', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'Tab',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('des', models.TextField(blank=True, max_length=300, null=True, verbose_name='des')),
            ],
            options={
                'verbose_name_plural': 'Work',
            },
        ),
    ]
