# Generated by Django 4.0.1 on 2022-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerheader',
            name='about_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
