# Generated by Django 4.0.4 on 2022-06-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerheader',
            name='instagram_link',
        ),
        migrations.AddField(
            model_name='footerheader',
            name='github_link',
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name='github_link'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='fb_link',
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name='fb_link'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name='twitter_link'),
        ),
    ]
