# Generated by Django 4.0.4 on 2022-05-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_skill_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=60, verbose_name='skill_title')),
                ('skill_percentage', models.IntegerField(verbose_name='skill_percentage')),
                ('image', models.ImageField(upload_to='media/index/Skill/', verbose_name='image')),
                ('color_bar', models.CharField(choices=[('#800000', 'Maroon'), ('#728FCE', 'LightPurple'), ('#800080', 'Purple'), ('#4863A0', 'Azure'), ('#566D7E', 'Marble'), ('#15317E ', 'Lapis'), ('#1E90FF', 'DeepSkyBlue'), ('#0041C2', '  Canary'), ('#7BCCB5', 'BlueGreen'), ('#6A5ACD', 'SlateBlue'), ('#8A2BE2 ', 'BlueViolet'), ('#57FEFF', 'Zircon')], max_length=60, verbose_name='color')),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
