# Generated by Django 4.0.1 on 2022-05-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
