# Generated by Django 4.0.1 on 2022-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_about_txt_footerheader_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright',
            field=models.CharField(blank=True, default='Copyright', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_txt_1',
            field=models.CharField(blank=True, default='This template is made with', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_txt_2',
            field=models.CharField(blank=True, default='by', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='all_rights_reserved',
            field=models.CharField(blank=True, default=' All rightsreserved', max_length=220, null=True),
        ),
    ]
