# Generated by Django 4.0.4 on 2022-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_skills_delete_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='color_bar',
            field=models.CharField(choices=[('#800000', 'Maroon'), ('#728FCE', 'LightPurple'), ('#800080', 'Purple'), ('#4863A0', 'Azure'), ('#566D7E', 'Marble'), ('#CD7F32', ' Bronze'), ('#FF8040', 'Orange'), ('#15317E ', 'Lapis'), ('#1E90FF', 'DeepSkyBlue'), ('#0041C2', '  Canary'), ('#7BCCB5', 'BlueGreen'), ('#6A5ACD', 'SlateBlue'), ('#8A2BE2 ', 'BlueViolet'), ('#57FEFF', 'Zircon')], max_length=60, verbose_name='color'),
        ),
    ]
