# Generated by Django 4.0.1 on 2022-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_footerheader_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerheader',
            name='follow_me_text_name',
            field=models.CharField(blank=True, default='FOLLOW ME', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='all_rights_reserved',
            field=models.CharField(blank=True, default=' All rights reserved', max_length=220, null=True),
        ),
    ]
