# Generated by Django 4.0.4 on 2022-05-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_skills_options_alter_skills_color_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBarAr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, default='/', help_text='eg: /page', max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'MenuBarAr',
            },
        ),
        migrations.CreateModel(
            name='MenuBarEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, default='/', help_text='eg: /page', max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'MenuBarEn',
            },
        ),
    ]
