# Generated by Django 4.0.4 on 2022-05-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_menubarar_menubaren'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menubarar',
            options={'verbose_name_plural': 'MenuBar Ar'},
        ),
        migrations.AlterModelOptions(
            name='menubaren',
            options={'verbose_name_plural': 'MenuBar En'},
        ),
    ]
