# Generated by Django 4.0.1 on 2022-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_footerheader_follow_me_text_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='cv_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hello',
            name='hire_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
