# Generated by Django 4.0.1 on 2022-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_hello_cv_link_hello_hire_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='cv',
            field=models.CharField(default='Get CV', max_length=50),
        ),
        migrations.AddField(
            model_name='hello',
            name='hire',
            field=models.CharField(default='Hire Me', max_length=50),
        ),
    ]
