# Generated by Django 4.0.1 on 2022-01-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_hello_cv_hello_hire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='image',
        ),
        migrations.AddField(
            model_name='hello',
            name='back_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/hello/'),
        ),
        migrations.AddField(
            model_name='hello',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/hello/'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='des',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
