# Generated by Django 4.0.1 on 2022-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_hello_image_hello_back_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myself',
            name='des',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
