# Generated by Django 4.0.1 on 2022-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_hello_name_alter_myself_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='myself',
            name='download_cv',
            field=models.CharField(default=' Download CV', max_length=50),
        ),
        migrations.AlterField(
            model_name='hello',
            name='des',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hello',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myself',
            name='des',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/myself/'),
        ),
    ]
