# Generated by Django 4.0.1 on 2022-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_myself_download_cv_alter_hello_des_alter_hello_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myself',
            name='download_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='cv_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='hire_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
