# Generated by Django 4.0.1 on 2022-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_myself_download_link_alter_hello_cv_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='des',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/call/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='name',
            field=models.CharField(default='call us now', max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
