# Generated by Django 4.0.1 on 2022-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_call_des_alter_call_image_alter_call_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='brand_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
        migrations.AddField(
            model_name='call',
            name='brand_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
        migrations.AddField(
            model_name='call',
            name='brand_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
        migrations.AddField(
            model_name='call',
            name='brand_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
        migrations.AddField(
            model_name='call',
            name='brand_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
        migrations.AddField(
            model_name='call',
            name='brand_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/brands/'),
        ),
    ]
