# Generated by Django 4.0.1 on 2022-01-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_call_brand_image_1_call_brand_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='brand_image_1',
            new_name='brand_image',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image_2',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image_3',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image_4',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image_5',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image_6',
        ),
    ]
