# Generated by Django 4.0.1 on 2022-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_rename_brand_image_1_call_brand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('availble', 'availble'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/index/work/popular/')),
            ],
        ),
        migrations.RenameField(
            model_name='call',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='clientsay',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='hello',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='myself',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='call',
            name='brand_image',
        ),
        migrations.AlterField(
            model_name='popular',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/work/latest/'),
        ),
    ]
