# Generated by Django 4.0.1 on 2022-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_tab_rename_name_call_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='status',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Latest', 'Latest'), ('Following', 'Following'), ('Upcoming', 'Upcoming')], max_length=50, null=True),
        ),
    ]
