# Generated by Django 4.0.1 on 2022-01-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_tab_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tab',
            new_name='all_Tab',
        ),
    ]
