# Generated by Django 4.0.1 on 2022-01-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_rename_tab_all_tab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_Tab',
            new_name='Tab',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Latest',
        ),
        migrations.DeleteModel(
            name='Popular',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
