# Generated by Django 4.0.1 on 2022-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_rename_all_tab_tab_delete_following_delete_latest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
