# Generated by Django 4.0.1 on 2022-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_contactinfo_address_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='Send_any_time',
            field=models.CharField(blank=True, default='Send us your query anytime!', max_length=70),
        ),
    ]
