# Generated by Django 4.0.1 on 2022-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_contactinfo_send_any_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerheader',
            name='site_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
