# Generated by Django 4.0.1 on 2022-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_alter_footerheader_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerheader',
            name='site_name',
            field=models.CharField(blank=True, default='Site Name', max_length=220, null=True),
        ),
    ]
