# Generated by Django 4.0.1 on 2022-04-27 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_alter_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name_plural': 'Call'},
        ),
        migrations.AlterModelOptions(
            name='clientsay',
            options={'verbose_name_plural': 'ClientSay'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'ContactInfo'},
        ),
        migrations.AlterModelOptions(
            name='footerheader',
            options={'verbose_name_plural': 'FooterHeader'},
        ),
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name_plural': 'Hello'},
        ),
        migrations.AlterModelOptions(
            name='myself',
            options={'verbose_name_plural': 'MySelf'},
        ),
        migrations.AlterModelOptions(
            name='newsletteruser',
            options={'verbose_name_plural': 'NewsletterUser'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='tab',
            options={'verbose_name_plural': 'Tab'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
        migrations.AlterField(
            model_name='call',
            name='des',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='call',
            name='experience',
            field=models.CharField(blank=True, default=' Years Experience Working', max_length=60, null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='call',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/call/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='call',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='call',
            name='title',
            field=models.CharField(default='call us now', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='call',
            name='years',
            field=models.IntegerField(blank=True, default='3', null=True, verbose_name='years'),
        ),
        migrations.AlterField(
            model_name='clientsay',
            name='big_dec',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='big_dec'),
        ),
        migrations.AlterField(
            model_name='clientsay',
            name='big_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='big_name'),
        ),
        migrations.AlterField(
            model_name='clientsay',
            name='des',
            field=models.TextField(max_length=400, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='clientsay',
            name='image',
            field=models.ImageField(upload_to='media/index/clientsay/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='clientsay',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Send_any_time',
            field=models.CharField(blank=True, default='Send us your query anytime!', max_length=70, verbose_name='Send_any_time'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_details',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='address_details'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='work_time',
            field=models.CharField(blank=True, default='Mon to Fri 9am to 6 pm', max_length=70, verbose_name='work_time'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright',
            field=models.CharField(blank=True, default='Copyright', max_length=220, null=True, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Copyright_date'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Copyright_link'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_txt_1',
            field=models.CharField(blank=True, default='This template is made with', max_length=220, null=True, verbose_name='Copyright_txt_1'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='Copyright_txt_2',
            field=models.CharField(blank=True, default='by', max_length=220, null=True, verbose_name='Copyright_txt_2'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='all_rights_reserved',
            field=models.CharField(blank=True, default=' All rights reserved', max_length=220, null=True, verbose_name='all_rights_reserved'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='fb_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='fb_link'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='follow_me_text_name',
            field=models.CharField(blank=True, default='follow_me_text_name', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='instagram_link'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/FollowMe/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='site_name',
            field=models.CharField(blank=True, max_length=220, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='footerheader',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='twitter_link'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='back_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/hello/', verbose_name='back_banner'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='cv',
            field=models.CharField(default='Get CV', max_length=50, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='cv_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='cv_link'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='des',
            field=models.TextField(blank=True, max_length=400, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='hello_name',
            field=models.CharField(default='hello', max_length=50, verbose_name='hello_name'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='hire',
            field=models.CharField(default='Hire Me', max_length=50, verbose_name='hire'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='hire_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='hire_link'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/hello/', verbose_name='image_banner'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='des',
            field=models.TextField(blank=True, max_length=400, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='download_cv',
            field=models.CharField(default=' Download CV', max_length=50, verbose_name='download_cv'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='download_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='download_link'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/myself/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data_added'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='service',
            name='big_dec',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='big_dec'),
        ),
        migrations.AlterField(
            model_name='service',
            name='big_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='big_name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='des',
            field=models.TextField(max_length=400, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='media/index/service/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='des',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/index/work/popular/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='status',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Latest', 'Latest'), ('Following', 'Following'), ('Upcoming', 'Upcoming')], max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='des',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='des'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
